# Generated by Django 4.0.6 on 2022-08-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.category'),
        ),
    ]
