# Generated by Django 4.0.6 on 2022-08-16 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_messages_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='form_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='message',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
